name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=20.3.3
  - mlflow=1.14.1
  - hydra-core=1.0.6
  - pip:
      - wandb==0.13.9  # 0.10.21
      - hydra-joblib-launcher==1.1.2
    # note: numpy newer version to get rid of
    # AttributeError (deprecation on 1.20)
      - numpy==1.23.5	  