name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.28.2  #2.24.0
  - pip=22.3.1      #20.3.3
  - mlflow=2.1.1     #1.14.1
  - hydra-core=1.3.1 #1.0.6
  - wandb=0.13.10
  - pip:
      - wandb==0.13.10
      - hydra-joblib-launcher==1.2.0 #1.1.2
      # own modification: add newer numpy version
      # to get rid of AttributeError: module 'numpy' has no attribute 'object'. See:
      # https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
      - numpy==1.23.5