wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1703298103.992555
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.8.12
      5: 0.13.10
      8:
      - 5
