name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.3  #1.2.3
  - pip=22.3.1    #20.3.3
  - scikit-learn=1.2.1  #0.24.1
  - wandb=0.13.10
  - pip:
      #- wandb==0.13.10   #0.10.21
      - numpy==1.23.5