name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.28.2  #2.24.0
  - pip=22.3.1       #20.3.3
  - wandb=0.13.10
  - pip:
      - wandb==0.13.10  #0.10.21
      - numpy==1.23.5